module.exports = {
    purge: ['./src/**/*.{js,jsx,ts,tsx}',  ],
    darkMode: false,
    theme: {
      screens: {
        'xs': '360px',
        'smint': '412px',
        'sm': '420px',
        'int': '480px',
        'md': '547px',
        'lg': '768px',
        'xl': '1024px',
        'xli': '1366px',
        '2xl': '1680px',
        'max': '1920px',
      },
      fontSize: {
        'pico': '0.1rem',
        'micro': '0.2rem',
        'smallest': '.5rem',
        'xs': '0.75rem',
        'smaller': '.813rem',
        'sm': '0.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        'small': '1.375rem',
        '2xl': '1.5rem',
        'blobsm': '1.75rem',
        'blobmed': '2rem',
        '4xl': '2.25rem',
        '6xl': '3rem',
        '7xl': '4.5rem',
        '8xl': '6rem',
        '9xl': '8rem',
        'titlesmall': '2.85rem',
        'title547': '5.6rem',
        'title1024': '7.6rem',
        'intermezzo360lg': '2.375rem',
        'intermezzo420lg': '2.7rem',
        'intermezzo547lg': '3.5rem',
        'intermezzo768lg': '4rem',
        'intermezzo1024lg': '5rem',
        'intermezzo1680lg': '7rem',
        'intermezzo1680sm': '2.5rem',
        'massive': '18rem',
        'extralg': '20rem',
        'detailsub': '5.25rem',
        'detailmd': '13rem',
        'detailsm': '10rem',
        'detailh2md': '3.8rem',
      },
      letterSpacing: {
        widest: '.3rem',
      },
      extend: {
        spacing: {
        'nav': '8.625rem',
        'dev-bottom-sm': '0.6rem',
        'dev-bottom-md': '0.9rem',
        'dev-bottom-lg': '1.1rem',
        'dev-bottom-xl': '1.6rem',
        'dev-top-sm': '0.34rem',
        'forms-top-sm': '6.125rem',
        'tools-lg': 'calc(38vw - 17rem)',
        'tools-contsm': '10vh',
        'tools-contmd': '20vh',
        'tools-contlg': '40vh',
        'tools-md': 'calc(38vw - 12rem)',
        'blob-right': '15%',
        'blobbie': '20%',
        'detcont': '55vw',
        'neg-1/6': 'calc(-100%/6)',
        },
        inset: {
          '1/5': '20%',
          '35': '35%',
          '2/5': '40%',
          '3/5': '60%',
          '4/5': '80%',
          'placeholder': '0.4rem',
          'up': '-9.375rem',
          'down': '9.375rem',
          'heroright': '60vh',
          'heroleft': '-50vh',
          'herodown': '10vh',
          'detailnav': '1.5rem',
          'offset': '-33.33333334vw',
          'neg-1/5': '-20%',
          'neg-1/3': 'calc(-100vw/3)',
          'neg-2/3': 'calc(-200vw/3)',
          'full': '-100vw',
          'half': '-50vw',
          'detailmax': '-40rem',
          'tenner': '10%',
          'herol': '-56.25rem',
          'herot': '11.25rem'
      
        },
        fill: {
          'light': '#E4E4E4',
          'dark': '#1E252E',
        },
        zIndex: {
        '-10': '-10',
        '100': '100',
        '200': '200',
        '150': '150',
        '300': '300',
        '400': '400',
        },
        textColor: {
          'dark': '#1E252E',
          'gold': '#B66C3B',
          'light': '#E4E4E4',
          'error': '#EF4444',
        },
        colors: {
          transparent: 'transparent',
          current: 'currentColor',
          'dark': '#1E252E',
          'gold': '#B66C3B',
          'light': '#E4E4E4',
        },
        fontFamily: {
          'reg': ['prep', 'playfair', 'serif'],
          'thin': ['prepthin', 'serif'],
          'light': ['preplight', 'serif'],
          'bold': ['prepbold', 'playfairbold', 'serif'],
          sans: ['josefin', 'sans-serif'],
          'josb': ['josefinbold', 'sans-serif'],
          'josefine': ['josefine', 'sans-serif'],
          'josethin': ['josethin'],
          'mendlight': ['mendlight', 'josefine'],
          'mendbold': ['mendbold'],
          'mendreg': ['mendreg, josefin'],
      },
      width: {
        'logo': '4.5rem',
        'formsxl': '45vw',
        '69': '68.75rem',
        'blob_1_sm': '71.5rem',
        '90': '90rem',
        '95': '95rem',
        '110': '110rem',
        '130': '130rem',
        '1/10': '10%',
        '3/10': '30%',
        '12/25': '48%',
        '55': '55%',
        '3/5': '60%',
        '70': '70%',
        '85': '87%',
        'over': '160vw',
        'detailhor': '166.6666667vw',
        'complete': '100vw',
        'detw': '33.33333334vw',
        'wider': '233.33333334vw',
        'mobile': '500vw',
        'half': '50vw',
        'tablet': '300vw',
        'phones': '40vw',
        'blobw': '60vw',
        'nearly': '90%',
        'phonesm': '80vw',
        'overlg': '140vw',
        'proj': '40rem',
        'double': '200vw',
        '5/3': 'calc(500vw/3)',
        '5/2': '250vw',
        '6vw': '600vw',
      },
      height: {
        '90': '90rem',
        '120': '120vh',
        '160': '160vh',
        'blob_1_lg': '45.8rem',
        'blob_1_sm': '40.4375rem',
        'bcard_sm': '30rem',
        'bcard_lg': '40rem',
        'bcard_xl': '50rem',
        'bcard_2xl': '60rem',
        'blobdeth': '60vh',
        'blobsm': '80vh',
        'liftsm': '20vh',
        'over': '70%',
        'blob_hero_sm': '31.25rem',
        'blob_hero_lg': '50vh',
        'cookies': '12vh',
        'cookiessm': '30vh',
      },
      maxWidth: {
        'smbutton': '6rem',
        'button': '10.8rem',
        'solobttn': '12rem',
        'button-cont': '32rem',
        'socials': '37.5rem',
        '120': '120rem',
        'textherosm': '55rem',
        'textheromd': '56.25rem',
        'textendxl': '63.5rem',
        'formsxl': '40vw',
        'detail': '40rem',
        'detail-cont': '46rem',
        'detail-blob': '60rem',
        'detail-blobxl': '96rem',
        'blobtext_int': '80vw',
        'blobtext_lg': '37.5rem',
        'screen': '100vw',
        'blobtext_med': '60vw',
      },
      maxHeight: {
        'lift': '60rem',
        'liftsm': '75vw',
        'logolg': '96rem',
        'det': '33.75rem',
        'heroimg': '112.5rem',
      },
      gridTemplateRows: {
        '8': 'repeat(8, minmax(0, 1fr))',
        '12': 'repeat(12, minmax(0, 1fr))'
      },
      lineHeight: {
        'title': '0.85',
        'snuggish': '1.1',
        'vloose': '3',
      },
      translate: {
        'neg-full': '-100%',
        'half': '-50%',
        'det': '-33.33333334vw',
      },
      backgroundImage: {
        'connect': "url('./app/assets/img/connect.png')",
        'online-warriors': "url('./app/assets/img/online-warriors.jpeg')",
        'ledger': "url('./app/assets/img/ledger.png')",
        'gentse-feesten': "url('./app/assets/img/gentsefeesten.png')",
        'codegram': "url('./app/assets/img/codegram.jpg')",
        'osoc': "url('./app/assets/img/osoc.png')",
        'arne-quinze': "url('./app/assets/img/aq.png')",
      },
      backgroundPosition: {
        'left-4': '-16rem center',
        'lefter': '-40rem center',
      },
      rotate: {
        'full': '360deg'
      },
      transitionDuration: {
        'slow': '2000ms'
      },
      transitionProperty: {
        'width': 'width',
        'opacity': 'opacity'
      },
      animation: {
        'spin-once': 'spinner 2s ease-in-out normal forwards',
        'fade-in': 'fader 0.8s cubic-bezier(0.4, 0, 0.6, 1) normal',
      },
      scale:  {
        '200': '2'
      },
      keyframes: {
         spinner: {
          'from': {transform: 'rotate(0deg)'},
          'to': {transform: 'rotate(180deg)' }
         },
         fader: {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.4 },
         }
      },
    }},
    variants: {
      fill: ['hover'],
      extend: {
        appearance: ['focus'],
        backgroundPosition: ['hover', 'focus'],
      },
    },
    plugins: [],
  }