module.exports = {
  mode: 'jit',
  purge: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    screens: {
      'xs': '360px',
      'sm': '420px',
      'int': '480px',
      'md': '547px',
      'lg': '768px',
      'xl': '1024px',
      'xli': '1366px',
      '2xl': '1680px',
    },
    fontSize: {
      'smallest': '.5rem',
      'xs': '0.75rem',
      'smaller': '.813rem',
      'sm': '0.875rem',
      'base': '1rem',
      'lg': '1.125rem',
      'xl': '1.25rem',
      'small': '1.375rem',
      '2xl': '1.5rem',
      'blobsm': '1.75rem',
      'blobmed': '2rem',
      '4xl': '2.25rem',
      '7xl': '4.5rem',
      '8xl': '6rem',
      'titlesmall': '2.85rem',
      'title547': '5.6rem',
      'title1024': '7.6rem',
      'intermezzo360lg': '2.375rem',
      'intermezzo420lg': '2.7rem',
      'intermezzo547lg': '3.5rem',
      'intermezzo768lg': '4rem',
      'intermezzo1024lg': '5rem',
      'intermezzo1680lg': '7rem',
      'intermezzo1680sm': '2.5rem',
    },
    letterSpacing: {
      widest: '.3rem',
    },
    extend: {
      spacing: {
      'nav': '8.625rem',
      'dev-bottom-sm': '0.6rem',
      'dev-bottom-md': '0.9rem',
      'dev-bottom-lg': '1.1rem',
      'dev-bottom-xl': '1.6rem',
      'dev-top-sm': '0.34rem',
      'forms-top-sm': '6.125rem',
      },
      inset: {
        '1/5': '20%',
        '35': '35%',
        '2/5': '40%',
        '3/5': '60%',
        'placeholder': '0.4rem',
        'up': '-9.375rem',
        'down': '9.375rem',
        'heroright': '60vh',
        'heroleft': '-50vh',
        'herodown': '10vh',
      },
      fill: {
        'light': '#E4E4E4'
      },
      zIndex: {
      '-10': '-10',
      },
      textColor: {
        'dark': '#1E252E',
        'gold': '#B66C3B',
        'light': '#E4E4E4',
        'error': '#EF4444',
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        'dark': '#1E252E',
        'gold': '#B66C3B',
        'light': '#E4E4E4',
      },
      fontFamily: {
        'reg': ['prep', 'playfair', 'serif'],
        'thin': ['prepthin', 'serif'],
        'light': ['preplight', 'serif'],
        'bold': ['prepbold', 'playfairbold', 'serif'],
        sans: ['josefin', 'sans-serif'],
        'josb': ['josefinbold', 'sans-serif'],
        'josefine': ['josefine', 'sans-serif'],
        'josethin': ['josethin'],
        'mendlight': ['mendlight', 'josefine'],
        'mendbol': ['mendbol'],
        'mendreg': ['mendreg, josefin'],
    },
    width: {
      'logo': '4.5rem',
      'formsxl': '45vw',
      '69': '68.75rem',
      'blob_1_sm': '71.5rem',
      '90': '90rem',
      '95': '95rem',
      '110': '110rem',
      '130': '130rem',
      '1/10': '10%',
      '12/25': '48%',
      '55': '55%',
      '3/5': '60%',
      '85': '87%',
      'over': '110vw',
      'detailhor': 'calc(500%/3)',
      'complete': '100vw',
      'detw': 'calc(100vw/3)',
      '80': '80vw',
      'ten': '10vw',
    },
    height: {
      '90': '90rem',
      '120': '120vh',
      '160': '160vh',
      'blob_1_lg': '45.8rem',
      'blob_1_sm': '40.4375rem',
      'bcard_sm': '30rem',
      'bcard_lg': '40rem',
      'bcard_xl': '50rem',
      'bcard_2xl': '60rem',
    },
    maxWidth: {
      'button': '10.8rem',
      'button-cont': '32rem',
      'socials': '37.5rem',
      '120': '120rem',
      'textherosm': '55rem',
      'textheromd': '56.25rem',
      'textendxl': '63.5rem',
      'formsxl': '40vw',
    },
    gridTemplateRows: {
      '8': 'repeat(8, minmax(0, 1fr))',
      '12': 'repeat(12, minmax(0, 1fr))'
    },
    lineHeight: {
      'title': '0.85',
    },
    translate: {
      'half': '-50%',
    },
    backgroundImage: {
      'connect': "url('./assets/img/connect.png')",
      '0': "url('./assets/img/online-warriors.jpeg')",
      '1': "url('./assets/img/gentsefeesten.jpg')",
      '2': "url('./assets/img/codegram.jpg')",
      '3': "url('./assets/img/osoc.png')",
      '4': "url('./assets/img/aq.png')",

    }
  }},
  variants: {
    fill: ['hover'],
    extend: {
      appearance: ['focus'],
    },
  },
  plugins: [],
}
